import React from "react";
import { PageHeader } from "@/components/PageHeader";
import { RoleBadge } from "@/components/RoleBadge";
import { DashboardCard } from "@/components/DashboardCard";
import { StatusBadge } from "@/components/StatusBadge";
import { mockPatientData } from "@/lib/mockData";
import {
  HeartPulse,
  Activity,
  Calendar,
  Share2,
  Building2,
  Wifi,
  FileText,
  Clock,
  CheckCircle2,
} from "lucide-react";

export default function PatientDashboardPage() {
  const p = mockPatientData;

  return (
    <div className="space-y-6">
      <PageHeader
        title={`Welcome, ${p.name}`}
        subtitle={`Gestational Age: ${p.gestationalAgeWeeks} Weeks • Location: ${p.location}`}
        roleBadge={<RoleBadge role="Patient" />}
      />

      {/* Main Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {/* Care Status */}
        <DashboardCard
          title="Current Care Pathway"
          icon={HeartPulse}
          highlight
          subtitle="Assigned ASHA: Meena Devi"
        >
          <div className="space-y-2">
            <span className="text-base font-extrabold text-slate-900 block">
              {p.careStatus}
            </span>
            <span className="text-xs text-slate-500 block">
              Pathway: High-Risk Maternal Care (Maternal Anemia & BP Pathway)
            </span>
          </div>
        </DashboardCard>

        {/* Preliminary Risk Status */}
        <DashboardCard
          title="Preliminary Risk Status"
          icon={Activity}
          subtitle="Screening flag generated by AI; validated by ASHA"
        >
          <div className="flex items-center justify-between">
            <StatusBadge status={p.preliminaryRiskStatus} />
            <span className="text-xs font-semibold text-rose-700 bg-rose-50 px-2 py-0.5 rounded border border-rose-100">
              Action Priority
            </span>
          </div>
          <p className="text-xs text-slate-600 mt-3 leading-relaxed">
            High blood pressure (148/92) and low Hb (8.2 g/dL) detected.
          </p>
        </DashboardCard>

        {/* Next Follow-up */}
        <DashboardCard
          title="Next Follow-up Visit"
          icon={Calendar}
          subtitle="Scheduled home visit by ASHA worker"
        >
          <div className="flex items-start gap-2 text-teal-900">
            <Clock className="w-4 h-4 text-teal-700 shrink-0 mt-1" />
            <span className="text-sm font-bold leading-snug">
              {p.nextFollowUp}
            </span>
          </div>
        </DashboardCard>
      </div>

      {/* Detailed Referral & Recommended Facility Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Active Referral Card */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2">
              <Share2 className="w-5 h-5 text-teal-700" />
              <h3 className="font-bold text-slate-900 text-base">
                Active Referral Tracker
              </h3>
            </div>
            <StatusBadge status="Pending Acceptance" />
          </div>

          <div className="space-y-3">
            <div>
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block">
                Referred To
              </span>
              <p className="text-sm font-bold text-slate-900 mt-0.5">
                {p.referralStatus}
              </p>
            </div>

            <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/60 text-xs text-slate-600 space-y-1">
              <div className="flex justify-between">
                <span className="text-slate-500">Referred By:</span>
                <span className="font-semibold text-slate-800">
                  {p.assignedASHA}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Reason:</span>
                <span className="font-semibold text-slate-800">
                  Gestational Hypertension & Severe Anemia
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Recommended Facility Card */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
            <Building2 className="w-5 h-5 text-teal-700" />
            <h3 className="font-bold text-slate-900 text-base">
              Recommended Healthcare Facility
            </h3>
          </div>

          <div className="space-y-3">
            <p className="text-sm font-bold text-slate-900">
              {p.recommendedFacility}
            </p>
            <p className="text-xs text-slate-600 leading-relaxed">
              Equipped with Emergency Obstetric Care (EmOC), Maternal ICU, and 24/7
              Blood Transfusion Facilities.
            </p>

            <div className="p-3 bg-teal-50/60 rounded-xl border border-teal-100 text-xs text-teal-900 flex items-center justify-between">
              <span>Approx distance: 8.5 km</span>
              <span className="font-bold text-teal-700">100% Subsidized Transit</span>
            </div>
          </div>
        </div>
      </div>

      {/* Vitals Summary & Offline Cache Placeholder */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Recorded Vitals Card */}
        <div className="lg:col-span-2 bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3 mb-4">
            <div className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-teal-700" />
              <h3 className="font-bold text-slate-900 text-base">
                Recent Vitals & Lab Measurements
              </h3>
            </div>
            <span className="text-xs text-slate-500">Captured by ASHA</span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <span className="text-[11px] font-semibold text-slate-500 block">
                Blood Pressure
              </span>
              <span className="text-base font-extrabold text-rose-700 mt-1 block">
                {p.vitals.bloodPressure}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <span className="text-[11px] font-semibold text-slate-500 block">
                Hemoglobin
              </span>
              <span className="text-base font-extrabold text-rose-700 mt-1 block">
                {p.vitals.hemoglobin}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <span className="text-[11px] font-semibold text-slate-500 block">
                Weight
              </span>
              <span className="text-base font-extrabold text-slate-800 mt-1 block">
                {p.vitals.weight}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-100">
              <span className="text-[11px] font-semibold text-slate-500 block">
                Pulse
              </span>
              <span className="text-base font-extrabold text-slate-800 mt-1 block">
                {p.vitals.pulse}
              </span>
            </div>
          </div>
        </div>

        {/* Offline Cache Status Card */}
        <div className="bg-slate-900 text-white rounded-2xl p-6 border border-slate-800 shadow-sm flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-3 text-teal-400">
              <Wifi className="w-5 h-5" />
              <h3 className="font-bold text-sm">Offline Storage Active</h3>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              Your patient health records, upcoming reminders, and active referral
              slips are stored locally on this device using IndexedDB.
            </p>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-400">
            <span className="flex items-center gap-1 text-emerald-400">
              <CheckCircle2 className="w-3.5 h-3.5" /> Synchronized
            </span>
            <span>{p.offlineSyncStatus.lastSynced}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
