import {
  AlertOctagon,
  AlertTriangle,
  Building2,
  Calendar,
  Clock,
  FileCheck,
  FileText,
  Inbox,
  LayoutDashboard,
  LogIn,
  MessageSquare,
  Mic,
  PackageCheck,
  Pill,
  RefreshCw,
  Share2,
  Stethoscope,
  UserPlus,
  Users,
} from "lucide-react";
import type { SearchableItem } from "./searchTypes";

/**
 * Header search catalog. Every href is an existing App Router page.
 * Role visibility is encoded in `audiences` so public users never see
 * worker/doctor/facility-admin destinations.
 */
export const SEARCHABLE_ROUTES: SearchableItem[] = [
  {
    id: "feedback-form",
    title: "Feedback Form",
    category: "Support",
    href: "/#feedback-section",
    keywords: ["feedback", "support", "report issue", "complaint", "help", "suggestion", "escalation"],
    icon: MessageSquare,
    audiences: ["public", "patient", "hw", "doctor", "facility"],
  },
  {
    id: "patient-facilities",
    title: "Nearby Hospitals / Facilities",
    category: "Facilities",
    href: "/patient/facilities",
    keywords: ["hospital", "hospitals", "facilities", "facility", "clinic", "phc", "chc", "nearby"],
    icon: Building2,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-symptoms",
    title: "Tell Symptoms",
    category: "Pages",
    href: "/patient/symptoms",
    keywords: ["symptom", "symptoms", "tell symptoms", "pain", "fever", "headache", "checklist"],
    icon: Mic,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-voice",
    title: "Voice Assistance",
    category: "Pages",
    href: "/patient/voice-assistant",
    keywords: ["voice", "speak", "tell symptoms", "audio", "mic", "assistant"],
    icon: Mic,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-emergency",
    title: "Emergency Help",
    category: "Pages",
    href: "/patient/emergency-help",
    keywords: ["emergency", "108", "102", "ambulance", "urgent", "help"],
    icon: AlertOctagon,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-appointments",
    title: "Book Appointment",
    category: "Pages",
    href: "/patient/appointments",
    keywords: ["appointment", "book", "doctor visit", "opd", "schedule"],
    icon: Calendar,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-records",
    title: "My Health Records",
    category: "Records",
    href: "/patient/records",
    keywords: ["records", "health records", "vitals", "history", "mcp"],
    icon: FileText,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-referrals",
    title: "Care Requests",
    category: "Pages",
    href: "/patient/referrals",
    keywords: ["care request", "referral", "referrals", "transfer"],
    icon: Share2,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-diagnostics",
    title: "Lab Tests",
    category: "Records",
    href: "/patient/diagnostics",
    keywords: ["lab", "labs", "test", "diagnostics", "report", "results"],
    icon: Stethoscope,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-medicines",
    title: "Medicines",
    category: "Medicines",
    href: "/patient/medicines",
    keywords: ["medicine", "medicines", "prescription", "pharmacy", "drugs"],
    icon: Pill,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-follow-ups",
    title: "Next Visits",
    category: "Pages",
    href: "/patient/follow-ups",
    keywords: ["visit", "follow-up", "follow up", "next visit"],
    icon: Clock,
    audiences: ["public", "patient"],
  },
  {
    id: "patient-documents",
    title: "Upload Records",
    category: "Records",
    href: "/patient/documents",
    keywords: ["upload", "document", "documents", "report", "file"],
    icon: FileCheck,
    audiences: ["public", "patient"],
  },
  {
    id: "login",
    title: "Login",
    category: "Pages",
    href: "/login",
    keywords: ["login", "sign in", "signin", "account"],
    icon: LogIn,
    audiences: ["public"],
  },
  {
    id: "register",
    title: "Sign Up",
    category: "Pages",
    href: "/register",
    keywords: ["sign up", "signup", "register", "create account"],
    icon: UserPlus,
    audiences: ["public"],
  },
  {
    id: "patient-home",
    title: "Patient Home",
    category: "Pages",
    href: "/patient/dashboard",
    keywords: ["home", "dashboard", "overview"],
    icon: LayoutDashboard,
    audiences: ["patient"],
  },
  {
    id: "hw-dashboard",
    title: "Health Worker Dashboard",
    category: "Pages",
    href: "/hw/dashboard",
    keywords: ["dashboard", "home", "overview", "asha", "anm"],
    icon: LayoutDashboard,
    audiences: ["hw"],
  },
  {
    id: "hw-patients",
    title: "My Patients",
    category: "Pages",
    href: "/hw/patients",
    keywords: ["patients", "people", "list"],
    icon: Users,
    audiences: ["hw"],
  },
  {
    id: "hw-register",
    title: "Register Patient",
    category: "Pages",
    href: "/hw/patients/register",
    keywords: ["register", "add patient", "new patient"],
    icon: UserPlus,
    audiences: ["hw"],
  },
  {
    id: "hw-high-risk",
    title: "Urgent Attention",
    category: "Pages",
    href: "/hw/high-risk",
    keywords: ["high risk", "urgent", "critical"],
    icon: AlertTriangle,
    audiences: ["hw"],
  },
  {
    id: "hw-referrals",
    title: "New Care Requests",
    category: "Pages",
    href: "/hw/referrals",
    keywords: ["care request", "referral", "referrals"],
    icon: Share2,
    audiences: ["hw"],
  },
  {
    id: "hw-follow-ups",
    title: "Visits Due & Missed",
    category: "Pages",
    href: "/hw/follow-ups",
    keywords: ["visit", "follow-up", "missed"],
    icon: Clock,
    audiences: ["hw"],
  },
  {
    id: "hw-sync",
    title: "Update Information",
    category: "Pages",
    href: "/hw/sync",
    keywords: ["sync", "offline", "update"],
    icon: RefreshCw,
    audiences: ["hw"],
  },
  {
    id: "doctor-dashboard",
    title: "Doctor Overview",
    category: "Pages",
    href: "/doctor/dashboard",
    keywords: ["dashboard", "overview", "review", "patients"],
    icon: LayoutDashboard,
    audiences: ["doctor"],
  },
  {
    id: "doctor-patients",
    title: "People Records",
    category: "Records",
    href: "/doctor/patients",
    keywords: ["patients", "records", "people"],
    icon: Users,
    audiences: ["doctor"],
  },
  {
    id: "doctor-care-requests",
    title: "Care Requests",
    category: "Pages",
    href: "/doctor/care-requests",
    keywords: ["care request", "referral", "referrals"],
    icon: Share2,
    audiences: ["doctor"],
  },
  {
    id: "doctor-schedule",
    title: "Today's Schedule",
    category: "Pages",
    href: "/doctor/schedule",
    keywords: ["schedule", "appointment", "opd", "today"],
    icon: Clock,
    audiences: ["doctor"],
  },
  {
    id: "facility-dashboard",
    title: "Facility Overview",
    category: "Pages",
    href: "/facility/dashboard",
    keywords: ["dashboard", "overview", "facility"],
    icon: LayoutDashboard,
    audiences: ["facility"],
  },
  {
    id: "facility-care-requests",
    title: "New Care Requests",
    category: "Pages",
    href: "/facility/care-requests",
    keywords: ["care request", "referral", "inbox"],
    icon: Inbox,
    audiences: ["facility"],
  },
  {
    id: "facility-patients",
    title: "People Expected Today",
    category: "Pages",
    href: "/facility/patients",
    keywords: ["patients", "people", "expected"],
    icon: Users,
    audiences: ["facility"],
  },
  {
    id: "facility-lab",
    title: "Lab Results",
    category: "Records",
    href: "/facility/lab-results",
    keywords: ["lab", "labs", "results", "diagnostics"],
    icon: Stethoscope,
    audiences: ["facility"],
  },
  {
    id: "facility-medicines",
    title: "Medicine Stock",
    category: "Medicines",
    href: "/facility/medicines",
    keywords: ["medicine", "medicines", "stock", "pharmacy"],
    icon: PackageCheck,
    audiences: ["facility"],
  },
];
