"""initial schema

Revision ID: 06fec59710b4
Revises:
Create Date: 2026-09-10 21:16:34.801580

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.models.types
from alembic import op

revision: str = "06fec59710b4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilities",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("facility_type", sa.String(length=64), nullable=False),
        sa.Column("village", sa.String(length=255), nullable=True),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("capabilities", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reorder_level", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "HEALTH_WORKER", "FACILITY_STAFF", "PATIENT", name="role_enum"),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "inventory_transactions",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("item_id", app.models.types.GUID(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("resulting_quantity", sa.Integer(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("village", sa.String(length=255), nullable=True),
        sa.Column("abha_id", sa.String(length=64), nullable=True),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("registered_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abha_id"),
    )
    op.create_table(
        "synced_changes",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("client_change_id", sa.String(length=128), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("PATIENT", "REFERRAL", "CARE_GAP", name="sync_entity_type_enum"),
            nullable=False,
        ),
        sa.Column("entity_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="sync_operation_enum"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_version", sa.Integer(), nullable=True),
        sa.Column("user_id", app.models.types.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "client_change_id", name="uq_device_client_change"),
    )
    op.create_table(
        "care_gaps",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("gap_type", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Enum("OPEN", "CLOSED", name="care_gap_status_enum"), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "referrals",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("from_facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("to_facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("specialty_needed", sa.String(length=128), nullable=True),
        sa.Column("urgency", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "IN_TRANSIT",
                "COMPLETED",
                "CANCELLED",
                name="referral_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("referrals")
    op.drop_table("care_gaps")
    op.drop_table("synced_changes")
    op.drop_table("patients")
    op.drop_table("inventory_transactions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("inventory_items")
    op.drop_table("facilities")
    # ### end Alembic commands ###
