"""rbac roles and patient user link

Revision ID: 8a1a1bdb2387
Revises: 06fec59710b4
Create Date: 2026-09-10 21:50:34.232377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types


revision: str = '8a1a1bdb2387'
down_revision: Union[str, None] = '06fec59710b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New RBAC roles (DOCTOR, FACILITY_ADMIN) added alongside the existing
    # ADMIN/HEALTH_WORKER/FACILITY_STAFF/PATIENT values. Postgres requires
    # ALTER TYPE ... ADD VALUE to run outside an explicit transaction block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE role_enum ADD VALUE IF NOT EXISTS 'FACILITY_ADMIN'")
        op.execute("ALTER TYPE role_enum ADD VALUE IF NOT EXISTS 'DOCTOR'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', app.models.types.GUID(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
    # Note: Postgres does not support removing enum values; downgrading the
    # role_enum type is intentionally left as a no-op.
