"""add maternal care entities

Revision ID: bd726bc84191
Revises: 8a1a1bdb2387
Create Date: 2026-09-10 22:13:04.378198

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.models.types
from alembic import op

revision: str = "bd726bc84191"
down_revision: str | None = "8a1a1bdb2387"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctor_availability",
        sa.Column("doctor_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("is_booked", sa.Boolean(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_availability_facility_id"),
        "doctor_availability",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "health_worker_profiles",
        sa.Column("user_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "cadre",
            sa.Enum("ASHA", "ANM", "OTHER", name="health_worker_cadre_enum"),
            nullable=False,
        ),
        sa.Column("area", sa.String(length=255), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_health_worker_profiles_facility_id"),
        "health_worker_profiles",
        ["facility_id"],
        unique=False,
    )
    op.create_table(
        "encounters",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("author_id", app.models.types.GUID(), nullable=True),
        sa.Column("encounter_type", sa.String(length=64), nullable=False),
        sa.Column("encounter_date", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounters_facility_id"), "encounters", ["facility_id"], unique=False)
    op.create_index(op.f("ix_encounters_patient_id"), "encounters", ["patient_id"], unique=False)
    op.create_table(
        "pregnancies",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("expected_delivery_date", sa.Date(), nullable=True),
        sa.Column("gravida", sa.Integer(), nullable=True),
        sa.Column("para", sa.Integer(), nullable=True),
        sa.Column(
            "risk_level", sa.Enum("LOW", "MEDIUM", "HIGH", name="risk_level_enum"), nullable=False
        ),
        sa.Column("risk_flags", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "TERMINATED", name="pregnancy_status_enum"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pregnancies_patient_id"), "pregnancies", ["patient_id"], unique=False)
    op.create_table(
        "prescriptions",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("encounter_id", app.models.types.GUID(), nullable=True),
        sa.Column("inventory_item_id", app.models.types.GUID(), nullable=False),
        sa.Column("prescribed_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("dosage_instructions", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISPENSED", "CANCELLED", name="prescription_status_enum"),
            nullable=False,
        ),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescribed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescriptions_encounter_id"), "prescriptions", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_facility_id"), "prescriptions", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_patient_id"), "prescriptions", ["patient_id"], unique=False
    )
    op.create_table(
        "screenings",
        sa.Column("encounter_id", app.models.types.GUID(), nullable=False),
        sa.Column("screening_type", sa.String(length=128), nullable=False),
        sa.Column("result", sa.String(length=255), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="screening_risk_level_enum"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screenings_encounter_id"), "screenings", ["encounter_id"], unique=False
    )
    op.create_table(
        "symptoms",
        sa.Column("encounter_id", app.models.types.GUID(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("onset_date", sa.Date(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_symptoms_encounter_id"), "symptoms", ["encounter_id"], unique=False)
    op.create_table(
        "vitals",
        sa.Column("encounter_id", app.models.types.GUID(), nullable=False),
        sa.Column("systolic_bp", sa.Integer(), nullable=True),
        sa.Column("diastolic_bp", sa.Integer(), nullable=True),
        sa.Column("pulse", sa.Integer(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("spo2", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vitals_encounter_id"), "vitals", ["encounter_id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("referral_id", app.models.types.GUID(), nullable=True),
        sa.Column("availability_id", app.models.types.GUID(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW", name="appointment_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["doctor_availability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referrals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointments_facility_id"), "appointments", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_table(
        "diagnostic_orders",
        sa.Column("patient_id", app.models.types.GUID(), nullable=False),
        sa.Column("facility_id", app.models.types.GUID(), nullable=True),
        sa.Column("encounter_id", app.models.types.GUID(), nullable=True),
        sa.Column("screening_id", app.models.types.GUID(), nullable=True),
        sa.Column("referral_id", app.models.types.GUID(), nullable=True),
        sa.Column("test_type", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ORDERED",
                "COLLECTED",
                "COMPLETED",
                "CANCELLED",
                name="diagnostic_order_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("ordered_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ordered_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referrals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_orders_encounter_id"),
        "diagnostic_orders",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_orders_facility_id"), "diagnostic_orders", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_orders_patient_id"), "diagnostic_orders", ["patient_id"], unique=False
    )
    op.create_table(
        "diagnostic_reports",
        sa.Column("diagnostic_order_id", app.models.types.GUID(), nullable=False),
        sa.Column("result_summary", sa.String(length=512), nullable=True),
        sa.Column("result_data", sa.Text(), nullable=True),
        sa.Column("reported_at", sa.DateTime(), nullable=False),
        sa.Column("reported_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnostic_order_id"],
            ["diagnostic_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reported_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("diagnostic_order_id"),
    )
    op.add_column("referrals", sa.Column("screening_id", app.models.types.GUID(), nullable=True))
    op.create_foreign_key(None, "referrals", "screenings", ["screening_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "referrals", type_="foreignkey")
    op.drop_column("referrals", "screening_id")
    op.drop_table("diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_orders_patient_id"), table_name="diagnostic_orders")
    op.drop_index(op.f("ix_diagnostic_orders_facility_id"), table_name="diagnostic_orders")
    op.drop_index(op.f("ix_diagnostic_orders_encounter_id"), table_name="diagnostic_orders")
    op.drop_table("diagnostic_orders")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_facility_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_vitals_encounter_id"), table_name="vitals")
    op.drop_table("vitals")
    op.drop_index(op.f("ix_symptoms_encounter_id"), table_name="symptoms")
    op.drop_table("symptoms")
    op.drop_index(op.f("ix_screenings_encounter_id"), table_name="screenings")
    op.drop_table("screenings")
    op.drop_index(op.f("ix_prescriptions_patient_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_facility_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_encounter_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_pregnancies_patient_id"), table_name="pregnancies")
    op.drop_table("pregnancies")
    op.drop_index(op.f("ix_encounters_patient_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_facility_id"), table_name="encounters")
    op.drop_table("encounters")
    op.drop_index(
        op.f("ix_health_worker_profiles_facility_id"), table_name="health_worker_profiles"
    )
    op.drop_table("health_worker_profiles")
    op.drop_index(op.f("ix_doctor_availability_facility_id"), table_name="doctor_availability")
    op.drop_table("doctor_availability")
    # ### end Alembic commands ###
